---
title: "PUBPOL 5390 Homework 2"
author: Thelonious Goerz
date: "Draft date: `r format(Sys.time(), '%d %B %Y')`"
output:
  pdf_document:
    number_sections: yes
linestretch: 1.5
fig_width: 5
fig_height: 2.5
csl: "/Users/theloniousgoerz/Academic/Professional/Resources/Citations/styles-master/american-sociological-association.csl"
editor_options:
  chunk_output_type: inline
geometry: "left=1in,right=1in,top=1in,bottom=1in"
number-sections: true
keep_tex: true
link-citations: yes
linkcolor: blue
font_size: 12pt
header-includes: 
  - \usepackage{framed} 
  - \usepackage{amsmath}
  - \usepackage{tcolorbox} 
  - \usepackage{pdflscape}
  - \newcommand{\blandscape}{\begin{landscape}}
  - \newcommand{\elandscape}{\end{landscape}}
  - \usepackage{multirow} 
  - \usepackage{xcolor} 
  - \usepackage{tabularray}
  - \def\independenT#1#2{\mathrel{\rlap{$#1#2$}\mkern2mu{#1#2}}} 
  - \usepackage{setspace} 
  - \usepackage{threeparttable}
  - \usepackage{booktabs}
  - \usepackage{siunitx}
  - \usepackage{tikz}
  - \usepackage{tabularray}
  - \usepackage{float}
  - \usepackage{graphicx}
  - \usepackage{rotating}
  - \usepackage[normalem]{ulem}
  - \UseTblrLibrary{booktabs}
  - \UseTblrLibrary{siunitx}
---

```{r setup, include=TRUE, results="hide", echo = FALSE, message = F}

 rm(list = objects())
 # THIS IS THE WIDTH OF THE CODE                                                ###
 knitr::opts_chunk$set(echo = F,
                       resuls = T, message = F, warning = F)
 
 # knitr::opts_chunk$set(fig.width = unit(16,"cm"), fig.height = unit(9,"cm"))
 
```

\doublespacing
\fontsize{12}{22}
\setstretch{2}
\baselineskip=29pt

```{r Load Packages}
rm(list = ls())
### Packages ###
library(readr)
library(tidyverse)
library(fixest)
library(modelsummary)
library(haven)
library(magrittr)
library(splines)
library(glmnet)
library(KernSmooth)
library(boot)
library(tidymodels)
library(here)

```

```{r Data}
# Problem 1 
Gsmall = read_csv(here("Data","births_for_class_Gsmall.csv"))
H = read_csv(here("Data","births_for_class_H.csv"))

```

# Question 1

```{r Feature Set}
set1 = c(
    "gestation_weeks",
    "mom_age",
    "mom_race_hispanic_status",
    "mom_educ")

set2 = c(    
    "mom_age",
    "mom_race_hispanic_status",
    "mom_educ",
    "gestation_weeks",
    "time",
    "in_hospital",
    "gestation_weeks"
    )

set3 = c(    
    "mom_age",
    "mom_race_hispanic_status",
    "mom_educ",
    "gestation_weeks",
    "time",
    "in_hospital",
    "gestation_weeks",
    "prior_births_living",
    "plurality",
    "residence_status",
    "mom_bmi",
    "dad_age"
    )

FS_1 = paste(
set1,
collapse = "+"
)

FS_2 = paste(
set2,
collapse = "+"
)

FS_3 = paste(
set3,
collapse = "+"
)
```

```{r}
# Label Train and Test Set 
training = Gsmall
testing = H
```

```{r Pre-allocate Results DF}
performance_df = 
  data.frame(
    Model = c("OLS","LASSO","RIDGE","ELASTIC NET"),
    Feature_set = c(rep("Small",4),rep("Medium",4),rep("Large",4)),
    `SD (Birthweight) In-sample` = c(rep(sd(Gsmall$birth_weight),12)),
    `SD (Birthweight) Out of Sample` = c(rep(sd(H$birth_weight),12)),
    `RMSE IS` = c(rep(NA_real_,12)),
    `RMSE CV` = c(rep(NA_real_,12)),
    `RMSE OOS` = c(rep(NA_real_,12)),
    lambda = c(rep(NA_real_,12)),
    alpha = c(rep(NA_real_,12)),
    check.names = F
  )

```

```{r OLS}
ols_function = function(outcome,
                        training,
                        testing,
                        FS_recipe
                        ){
## SD Y ------------------------------
is_sd_y = sd(training[[outcome]])
os_sd_y = sd(testing[[outcome]])
## Define Model ------------------------------
ols = linear_reg(
  mode = "regression",
  engine = "lm"
) 
## Define Workflow ------------------------------
ols_workflow = 
 workflow() %>% 
  add_model(ols) %>% 
  add_recipe(FS_recipe)

## Fit Model -------------------------------------
fit_ols =
  ols_workflow %>% 
  fit(data = training)

## Obtain Predictions -----------------------------
ols_oos = predict(fit_ols,testing)
  
# Calculate RMSE ---------------------------------

## Combine Train-Test predictions and Outcomes into a DF 
ols_gof_train_df = data.frame(
  estimate = as.numeric(predict(fit_ols,training)$.pred),
  truth = unlist(fit_ols$pre$mold$outcomes[[outcome]]))

ols_gof_test_df = data.frame(
  estimate = as.numeric(ols_oos$.pred),
  truth = as.numeric(testing[[outcome]]))

## Calculate RMSE ------------------------------
ols_train_rmse = rmse(
     data = ols_gof_train_df,
     truth,
     estimate)

ols_test_rmse = rmse(
     data = ols_gof_test_df,
     truth,
     estimate)
# Return Items ------------------------------
return(
  data.frame(
    Model = "OLS",
    in_sample_sd_y = is_sd_y,
    oo_sample_sd_y = os_sd_y,
    in_sample_rmse = ols_train_rmse$.estimate,
    oo_sample_rmse = ols_test_rmse$.estimate,
    n_predictors = ncol(fit_ols$pre$mold$predictors)
  )
)
}
```

```{r Run OLS For Each Feature Set}
## Create Recipes 
FS_recipe_1 = recipe(as.formula(paste0("birth_weight","~",FS_1)), 
         data = training) %>%
         step_zv()

FS_recipe_2 = recipe(as.formula(paste0("birth_weight","~",FS_2)), 
         data = training) %>%
  step_mutate(
    across(c(
    mom_race_hispanic_status,
    mom_educ,
    gestation_weeks
    ), 
    as.factor)
  ) %>% 
    step_dummy(all_nominal_predictors(),
             one_hot = T) %>% 
  step_zv(all_predictors())

FS_recipe_3 = recipe(as.formula(paste0("birth_weight","~",FS_3)), 
         data = training) %>%
  step_mutate(
    across(c(
    mom_race_hispanic_status,
    mom_educ,
    gestation_weeks,
    time,
    ), 
    as.factor)
  ) %>% 
    step_dummy(all_nominal_predictors(),
                one_hot = T) %>% 
  step_spline_b(mom_age,
                deg_free = 6,
                degree = 3,
                keep_original_cols = T) %>%
  step_zv(all_predictors())

# Run OLS Function on feature sets 
ols_fs_1 = ols_function("birth_weight",
    FS_recipe = FS_recipe_1,
    training = training,
    testing = testing)

ols_fs_2 = ols_function("birth_weight",
    FS_recipe = FS_recipe_2,
    training = training,
    testing = testing) 

ols_fs_3 = ols_function("birth_weight",
    FS_recipe = FS_recipe_3,
    training = training,
    testing = testing) 

### Save Metrics ###

rbind(ols_fs_1,
      ols_fs_2,
      ols_fs_3)
# why are these not chnaging? hmm 
```

```{r LASSO}
regularize_function = function(outcome,
                        training,
                        testing,
                        FS_recipe,
                        type,
                        n_folds,
                        grid_max
                        ){
## SD Y ------------------------------
is_sd_y = sd(training[[outcome]])
os_sd_y = sd(testing[[outcome]])
## Tune Parameters ------------------------------
## Pick Model

## Define folds 
folds = vfold_cv(training,v = n_folds) 

if (type == "LASSO"){
model_tune = linear_reg(
  mode = "regression",
  engine = "glmnet",
  mixture = 1, 
  penalty = tune()
) 
# Cross-Validate
cv_lambda = tune_grid(model_tune, 
                      FS_recipe,
                      resamples = folds, 
                      tune = penalty,
                      grid = expand.grid(penalty = 0:grid_max))

# Pick lambda # 
best_penalty = as.numeric(show_best(cv_lambda)[1,"penalty"])
best_mixture = 1

} else if (type == "Ridge"){
model_tune = linear_reg(
  mode = "regression",
  engine = "glmnet",
  mixture = 0, 
  penalty = tune()
) 
# Cross-Validate
cv_lambda = tune_grid(model_tune, 
                      FS_recipe,
                      resamples = folds, 
                      tune = penalty,
                      grid = expand.grid(penalty = 0:grid_max))

# Pick lambda # 
best_penalty = as.numeric(show_best(cv_lambda)[1,"penalty"])
best_mixture = 0

  
} else if (type == "Elastic"){
model_tune = linear_reg(
  mode = "regression",
  engine = "glmnet",
  mixture = tune(), 
  penalty = tune()
) 
# Cross-Validate 

cv_pick = tune_grid(model_tune, 
                      FS_recipe,
                      resamples = folds, 
                      tune = c(penalty,mixture),
                      grid = expand.grid(penalty = 0:grid_max,
                                         mixture = c(.25,.5,.75)))

# Pick lambda # 
best_penalty = as.numeric(show_best(cv_pick)[1,"penalty"])
best_mixture = as.numeric(show_best(cv_pick)[1,"mixture"])
}

# ------------------------------------------------------------
# Declare Model # 
regularized_model = linear_reg(
  mode = "regression",
  engine = "glmnet",
  mixture = best_mixture, 
  penalty = best_penalty
) 
## Define Workflow ------------------------------
rglr_workflow = 
 workflow() %>% 
  add_model(regularized_model) %>% 
  add_recipe(FS_recipe)

## Fit Model -------------------------------------
fit_rglr =
  rglr_workflow %>% 
  fit(data = training)

## Obtain Predictions -----------------------------
rglr_oos = predict(fit_rglr,testing)

tidy_coefficients <- fit_rglr %>%
      extract_fit_parsnip() %>%
      tidy()
    # Filter for non-zero coefficients (selected predictors)
    n_terms <- tidy_coefficients %>%
      filter(estimate != 0) %>%
      pull(term) %>% 
      length() %>% 
      as.numeric()
  
# Calculate RMSE ---------------------------------
## Combine Train-Test predictions and Outcomes into a DF 
rglr_gof_train_df = data.frame(
  estimate = as.numeric(predict(fit_rglr,training)$.pred),
  truth = unlist(fit_rglr$pre$mold$outcomes[[outcome]]))

rglr_gof_test_df = data.frame(
  estimate = as.numeric(rglr_oos$.pred),
  truth = as.numeric(testing[[outcome]]))

## Calculate RMSE ------------------------------
rglr_train_rmse = rmse(
     data = rglr_gof_train_df,
     truth,
     estimate)

rglr_test_rmse = rmse(
     data = rglr_gof_test_df,
     truth,
     estimate)
# Return Items ------------------------------
 return(
   data.frame(
     Model = {{type}},
     in_sample_sd_y = is_sd_y,
     oo_sample_sd_y = os_sd_y,
     in_sample_rmse = rglr_train_rmse$.estimate,
     oo_sample_rmse = rglr_test_rmse$.estimate,
     n_predictors = n_terms,
     mixture = best_mixture,
     penalty = best_penalty
   )
 ) 

}

```


```{r Run Regularized Regressions}
set.seed(9999)
# Run LASSO Models ------------------------------------- # 
# 
# -------------------------------------------------------#

lasso_FS_1 = regularize_function(outcome = "birth_weight",
                        training = training,
                        testing =  testing,
                        FS_recipe = FS_recipe_1,
                        type = "LASSO",
                        n_folds = 10,
                        grid_max = 30
                        )

lasso_FS_2 = regularize_function(outcome = "birth_weight",
                        training = training,
                        testing =  testing,
                        FS_recipe = FS_recipe_2,
                        type = "LASSO",
                        n_folds = 10,
                        grid_max = 30
                        )

lasso_FS_3 = regularize_function(outcome = "birth_weight",
                        training = training,
                        testing =  testing,
                        FS_recipe = FS_recipe_3,
                        type = "LASSO",
                        n_folds = 10,
                        grid_max = 30
                        )

set.seed(9999)
# Run RIDGE Models ------------------------------------- # 
# 
# -------------------------------------------------------#

ridge_FS_1 = regularize_function(outcome = "birth_weight",
                        training = training,
                        testing =  testing,
                        FS_recipe = FS_recipe_1,
                        type = "Ridge",
                        n_folds = 10,
                        grid_max = 50
                        )

ridge_FS_2 = regularize_function(outcome = "birth_weight",
                        training = training,
                        testing =  testing,
                        FS_recipe = FS_recipe_2,
                        type = "Ridge",
                        n_folds = 10,
                        grid_max = 50
                        )

ridge_FS_3 = regularize_function(outcome = "birth_weight",
                        training = training,
                        testing =  testing,
                        FS_recipe = FS_recipe_3,
                        type = "Ridge",
                        n_folds = 10,
                        grid_max = 50
                        )

# Run Elastic Net Models ------------------------------------- # 
# 
# -------------------------------------------------------------#

elastic_FS_1 = regularize_function(outcome = "birth_weight",
                        training = training,
                        testing =  testing,
                        FS_recipe = FS_recipe_1,
                        type = "Elastic",
                        n_folds = 10,
                        grid_max = 50
                        )

elastic_FS_2 = regularize_function(outcome = "birth_weight",
                        training = training,
                        testing =  testing,
                        FS_recipe = FS_recipe_2,
                        type = "Elastic",
                        n_folds = 10,
                        grid_max = 50
                        )

elastic_FS_3 = regularize_function(outcome = "birth_weight",
                        training = training,
                        testing =  testing,
                        FS_recipe = FS_recipe_3,
                        type = "Elastic",
                        n_folds = 10,
                        grid_max = 50
                        )




# Look at Models
rbind(lasso_FS_1,
      lasso_FS_2,
      lasso_FS_3,
      # Ridge
      ridge_FS_1,
      ridge_FS_2,
      ridge_FS_3,
      # Elastic
      elastic_FS_1,
      elastic_FS_2,
      elastic_FS_3
      )
```





