---
title: "Self-Fullfilling Prophecy?: Predicting Longevity and Mortality Using Subjective Mortality Expectations in the HRS"
author: |
  | Thelonious Goerz
  | PUBPOL 5390
date: "Draft date: `r format(Sys.time(), '%d %B %Y')`"
output:
  pdf_document:
    number_sections: yes
linestretch: 1.5
fig_width: 5
fig_height: 2.5
csl: "/Users/theloniousgoerz/Academic/Professional/Resources/Citations/styles-master/american-sociological-association.csl"
editor_options:
  chunk_output_type: inline
  markdown: 
    wrap: 72
geometry: "left=1in,right=1in,top=1in,bottom=1in"
number-sections: true
keep_tex: true
link-citations: yes
linkcolor: blue
font_size: 12pt
header-includes: 
  - \usepackage{framed} 
  - \usepackage{amsmath}
  - \usepackage{tcolorbox} 
  - \usepackage{pdflscape}
  - \newcommand{\blandscape}{\begin{landscape}}
  - \newcommand{\elandscape}{\end{landscape}}
  - \usepackage{multirow} 
  - \usepackage{xcolor} 
  - \usepackage{tabularray}
  - \def\independenT#1#2{\mathrel{\rlap{$#1#2$}\mkern2mu{#1#2}}} 
  - \usepackage{setspace} 
  - \usepackage{threeparttable}
  - \usepackage{booktabs}
  - \usepackage{siunitx}
  - \usepackage{tikz}
  - \usepackage{tabularray}
  - \usepackage{float}
  - \usepackage{graphicx}
  - \usepackage{rotating}
  - \usepackage[normalem]{ulem}
  - \UseTblrLibrary{booktabs}
  - \UseTblrLibrary{siunitx}
  - \newcommand{\tinytableTabularrayUnderline}[1]{\underline{#1}}
  - \newcommand{\tinytableTabularrayStrikeout}[1]{\sout{#1}}
  - \NewTableCommand{\tinytableDefineColor}[3]{\definecolor{#1}{#2}{#3}}
bibliography: references.bib
---

```{r setup, include=TRUE, results="hide", echo = FALSE, message = F}

 rm(list = objects())
 # THIS IS THE WIDTH OF THE CODE                                                ###
 knitr::opts_chunk$set(echo = F,
                       resuls = T, message = F, warning = F)
 
 # knitr::opts_chunk$set(fig.width = unit(16,"cm"), fig.height = unit(9,"cm"))
 
```

\fontsize{10}{10}

\section{Background}

The extent to which we can predict mortality well matters for
understanding population health. Recent work shows that individual-level
mortality and longevity prediction is challenging, with uncertainty
remaining high even with big microdata and rich individual-level
covariates [@badolato2023; @breen_demographic_2023]. Past work has
employed subjective mortality expectations to aid in interpreting the
predictive performance of models, but overlooked their role as focal
features. While individuals are not very good at predicting their own
mortality and there are noted inequalities in accuracy by social group,
whether subjective probabilities, however flawed, can be used in a
prediction model as "utility features" [@kose] in combination with other
strongly predictive variables (e.g., education, income, age, health) to
achieve gains in predictive performance is currently unexplored. This
project builds upon past efforts by testing the predictive performance
of subjective life expectancy measures to (1) predict individual
longevity and (2) predict survival past threshold ages (e.g., 75 years)
relative to models without expectations.

\section{Policy Relevance}

There are a variety of substantive and policy relevant reasons for
trying to obtain accurate mortality predictions. First, predicting
mortality from individual-level data is important for forecasting
population longevity in the future, especially by social groups or
categories that are not readily available from tabular data. Generating
accurate predictions can inform public health policy decisions
allocating resources to populations ar older ages based on predicted
life expectancy with morbidities, disabilities, disease, loneliness, and
other chronic conditions [@raymo2022]. Second, because research
documents notable inequalities in the predictability of mortality for
different social groups, the incorporation of subjective measures may
improve predictive accuracy and thereby contribute to efforts to narrow
mortality and longevity inequalities (e.g., by race).

\section{Outcomes}

\input{./Output/02_outcome_table.tex}

\section{Data}

This project will use individual-level longitudinal from the Health and
Retirement Study (HRS) to predict mortality. The HRS is a
population-representative sample of 20,000 adults 55 years an older that
contains information on income, wealth, health, education, and
subjective expectations. The HRS also tracks mortality outcomes for the
duration of individuals' participation in the study, making it an ideal
dataset to use for predicting mortality because of its granularity,
covariate richness, and sample size. The repeated-measures nature of
these data also opens up additional possibilities for predictive
performance because we observe individuals between 2 and 8 waves (4-16
years). Table 2 describes some key features of the sample. I anticipate
that the N for this sample will be approximately $170,000$ and the K
will be between $82-100$. This is before any binning or data
transformations.
\input{./Output/01_descriptive_table.tex}


\section{To Do}

\begin{itemize}
\item Tables: Table comparing in and out-of sample GOF measures and
percent improvement (over OLS) measures for continuous and binary
predictors across models (OLS, Probit (for binary), Ridge, LASSO, Random
Forest, XGBoost, and potentially Artificial Neural Network) between
models with and without utility feature-subjective probabilities
\item Figures: Calibration plots, AUC (for binary), variable importance
plot, comparison between models with and without
utility-feature-subjective probabilities
\end{itemize}
\pagebreak
\section{References}

